//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Background
    {
        public Background()
        {
            this.Questionnaires = new HashSet<Questionnaire>();
        }
    
        public int ID { get; set; }
        public byte[] image { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Questionnaire> Questionnaires { get; set; }
    }
}
