//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pin
    {
        public int ID { get; set; }
        public int questionnaireID { get; set; }
        public int questionID { get; set; }
        public long x { get; set; }
        public long y { get; set; }
        public int thumbnailID { get; set; }
        public int order { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual Thumbnail Thumbnail { get; set; }
    }
}
