//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTheme
    {
        public int ID { get; set; }
        public int questionID { get; set; }
        public int themeID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
