//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.ClosedAnswers = new HashSet<ClosedAnswer>();
            this.OpenAnswers = new HashSet<OpenAnswer>();
            this.Pins = new HashSet<Pin>();
            this.QuestionThemes = new HashSet<QuestionTheme>();
        }
    
        public int ID { get; set; }
        public string type { get; set; }
        public short points { get; set; }
        public string infoText { get; set; }
        public string infoYoutubeURL { get; set; }
        public string text { get; set; }
    
        public virtual ICollection<ClosedAnswer> ClosedAnswers { get; set; }
        public virtual ICollection<OpenAnswer> OpenAnswers { get; set; }
        public virtual ICollection<Pin> Pins { get; set; }
        public virtual ICollection<QuestionTheme> QuestionThemes { get; set; }
    }
}
