//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        public Questionnaire()
        {
            this.Pins = new HashSet<Pin>();
            this.ScoreBoards = new HashSet<ScoreBoard>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public int backgroundID { get; set; }
    
        public virtual Background Background { get; set; }
        public virtual ICollection<Pin> Pins { get; set; }
        public virtual ICollection<ScoreBoard> ScoreBoards { get; set; }
    }
}
