//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreBoard
    {
        public int ID { get; set; }
        public string userID { get; set; }
        public Nullable<long> score { get; set; }
        public int questionnaireID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
    }
}
