//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducateMe4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thumbnail
    {
        public Thumbnail()
        {
            this.Pins = new HashSet<Pin>();
        }
    
        public int ID { get; set; }
        public byte[] image { get; set; }
        public string name { get; set; }
        public string imageType { get; set; }
    
        public virtual ICollection<Pin> Pins { get; set; }
    }
}
